CREATE TABLE `srbsoh` (
  `OHHLIN` varchar(256) DEFAULT NULL,
  `OHORNO` varchar(256) NOT NULL,
  `OHHAND` varchar(256) DEFAULT NULL,
  `OHCUNO` varchar(256) DEFAULT NULL,
  `OHNAME` varchar(256) DEFAULT NULL,
  `OHOVAL` decimal(15,6) DEFAULT NULL,
  `SCRCCD` varchar(256) DEFAULT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=574 DEFAULT CHARSET=utf8;
